### ISSUE TITLE
Magento 2.3 Compatibility 

### ISSUE THREAD

**Issue by tschirmer** [mwr/ext-magento2-mwltr-filesystem-filedriver#2]
This module works great for 2.2, but in 2.3 they've added more path validation, so that if you're access your vendor directory outside the root, it'll causes problems on generation:

```
bin/magento setup:static-content:deploy 
In PathValidator.php line 63:                                                                         
Path "/path/to/magento-root/vendor/magento/module-customer/view/frontend/templates/additionalinfocustomer.phtml" cannot be used with directory "/path/outside/magento-root/httpdocs/" 
```

**Comment by mwr** [comment]
Thanks for checking. 
I did not have time to check this module with 2.3. Will check if I can reproduce and see how the PathValidator works.
Maybe there's an easy workaround

**Comment by mwr** [comment]
Seems like this module is no longer compatible since the method getRelativePath has been completely removed. I am setting the compatible versions of magento-framework in the composer.json
